import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Button from 'react-bootstrap/Button'
export default function Home() {
  const caza = async () => {
    const res = await fetch('http://localhost:3000/api/hello');
    const result = await res.json();
    console.log('Result')
    window.alert(result.answer)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>CAZA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          CAZA
        </h1>
        <p className={styles.description}>
          Compliant Anonymous ZKP Authentication
        </p>


        <Button onClick={caza} className={styles.grid}>
   
          <a
            className={styles.card}
          >
            <h2>Auth</h2>
            <p>
            </p>
          </a>
        </Button>
      </main>

      <footer className={styles.footer}>
        <a
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/ledger.svg" alt="Ledger Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
